[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ml_pipeline_with_mlflow_projecy"
version = "0.1.0"
description = "A machine learning pipeline with MLflow"
authors = [
    {name = "RajRajputGit"}

]
requires-python = ">=3.10"
dependencies = [
    "dvc",
    "scikit-learn",
    "mlflow",
    "dvc-s3",
    "dagshub"
]